name: MERN App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Build the frontend (client)
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to local server
        run: |
          sudo mkdir -p /var/www/mern-app
          sudo cp -r . /var/www/mern-app

      - name: Restart PM2
        run: |
          pm2 restart mern-backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
