name: MERN App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies for the server
        run: |
          cd server
          npm install

      - name: Install dependencies and build the client
        run: |
          cd client
          # Debugging: List files in the current directory
          echo "Current directory after cd client:"
          pwd
          ls -la
          npm install
          npm run build

      - name: Deploy to local server
        run: |
          # Debugging: List files in the current directory
          echo "Current directory before copying to server:"
          pwd
          ls -la
          sudo mkdir -p /var/www/mern-app
          sudo cp -r . /var/www/mern-app

      - name: Restart PM2
        run: |
          pm2 restart mern-backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
